schema-version = "1.13.0"

[install]
gotools.pkg-path = "gotools"
go.pkg-path = "go"
gopls.pkg-path = "gopls"
go-task.pkg-path = "go-task"

[hook]
on-activate = '''
  export GOPATH="$FLOX_ENV_CACHE/go"
  export PATH="$GOPATH/bin:$PATH"
'''

[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]

